name: Automatically deploy production backend 
on: 
  push:
    branches: 
    - main
    
jobs:
  build:
    name: Automatically deploy production backend on main change -> small footprint
    runs-on: ubuntu-latest
    steps:
    - name: git pull on existing local repo -> small footprint
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetNodeAPI
          git pull
          git status
          yarn install
          pm2 reload prod-pm2.ecosystem.config.js --watch --ignore-watch="node_modules"
